using System;
using System.ComponentModel;

namespace AppleITunes {
	public partial class Search {
		public enum Country {
			[Description("Andorra")] Andorra,
			[Description("United Arab Emirates")] UnitedArabEmirates,
			[Description("Afghanistan")] Afghanistan,
			[Description("Antigua and Barbuda")] AntiguaAndBarbuda,
			[Description("Anguilla")] Anguilla,
			[Description("Albania")] Albania,
			[Description("Armenia")] Armenia,
			[Description("Angola")] Angola,
			[Description("Antarctica")] Antarctica,
			[Description("Argentina")] Argentina,
			[Description("American Samoa")] AmericanSamoa,
			[Description("Austria")] Austria,
			[Description("Australia")] Australia,
			[Description("Aruba")] Aruba,
			[Description("Åland Islands")] ÅlandIslands,
			[Description("Azerbaijan")] Azerbaijan,
			[Description("Bosnia and Herzegovina")] BosniaAndHerzegovina,
			[Description("Barbados")] Barbados,
			[Description("Bangladesh")] Bangladesh,
			[Description("Belgium")] Belgium,
			[Description("Burkina Faso")] BurkinaFaso,
			[Description("Bulgaria")] Bulgaria,
			[Description("Bahrain")] Bahrain,
			[Description("Burundi")] Burundi,
			[Description("Benin")] Benin,
			[Description("Saint Barthélemy")] SaintBarthélemy,
			[Description("Bermuda")] Bermuda,
			[Description("Brunei Darussalam")] BruneiDarussalam,
			[Description("Bolivia, Plurinational State of")] BoliviaPlurinationalStateOf,
			[Description("Bonaire, Sint Eustatius and Saba")] BonaireSintEustatiusandSaba,
			[Description("Brazil")] Brazil,
			[Description("Bahamas")] Bahamas,
			[Description("Bhutan")] Bhutan,
			[Description("Bouvet Island")] BouvetIsland,
			[Description("Botswana")] Botswana,
			[Description("Belarus")] Belarus,
			[Description("Belize")] Belize,
			[Description("Canada")] Canada,
			[Description("Cocos (Keeling) Islands")] CocosKeelingIslands,
			[Description("Congo, the Democratic Republic of the")] CongoTheDemocraticRepublicOfThe,
			[Description("Central African Republic")] CentralAfricanRepublic,
			[Description("Congo")] Congo,
			[Description("Switzerland")] Switzerland,
			[Description("Côte d'Ivoire")] CôtedIvoire,
			[Description("Cook Islands")] CookIslands,
			[Description("Chile")] Chile,
			[Description("Cameroon")] Cameroon,
			[Description("China")] China,
			[Description("Colombia")] Colombia,
			[Description("Costa Rica")] CostaRica,
			[Description("Cuba")] Cuba,
			[Description("Cabo Verde")] CaboVerde,
			[Description("Curaçao")] Curaçao,
			[Description("Christmas Island")] ChristmasIsland,
			[Description("Cyprus")] Cyprus,
			[Description("Czech Republic")] CzechRepublic,
			[Description("Germany")] Germany,
			[Description("Djibouti")] Djibouti,
			[Description("Denmark")] Denmark,
			[Description("Dominica")] Dominica,
			[Description("Dominican Republic")] DominicanRepublic,
			[Description("Algeria")] Algeria,
			[Description("Ecuador")] Ecuador,
			[Description("Estonia")] Estonia,
			[Description("Egypt")] Egypt,
			[Description("Western Sahara")] WesternSahara,
			[Description("Eritrea")] Eritrea,
			[Description("Spain")] Spain,
			[Description("Ethiopia")] Ethiopia,
			[Description("Finland")] Finland,
			[Description("Fiji")] Fiji,
			[Description("Falkland Islands (Malvinas)")] FalklandIslands,
			[Description("Micronesia, Federated States of")] MicronesiaFederatedStatesOf,
			[Description("Faroe Islands")] FaroeIslands,
			[Description("France")] France,
			[Description("Gabon")] Gabon,
			[Description("United Kingdom")] UnitedKingdom,
			[Description("Grenada")] Grenada,
			[Description("Georgia")] Georgia,
			[Description("French Guiana")] FrenchGuiana,
			[Description("Guernsey")] Guernsey,
			[Description("Ghana")] Ghana,
			[Description("Gibraltar")] Gibraltar,
			[Description("Greenland")] Greenland,
			[Description("Gambia")] Gambia,
			[Description("Guinea")] Guinea,
			[Description("Guadeloupe")] Guadeloupe,
			[Description("Equatorial Guinea")] EquatorialGuinea,
			[Description("Greece")] Greece,
			[Description("South Georgia and the South Sandwich Islands")] SouthGeorgiaAndtheSouthSandwichIslands,
			[Description("Guatemala")] Guatemala,
			[Description("Guam")] Guam,
			[Description("Guinea-Bissau")] GuineaBissau,
			[Description("Guyana")] Guyana,
			[Description("Hong Kong")] HongKong,
			[Description("Heard Island and McDonald Islands")] HeardIslandAndMcDonaldIslands,
			[Description("Honduras")] Honduras,
			[Description("Croatia")] Croatia,
			[Description("Haiti")] Haiti,
			[Description("Hungary")] Hungary,
			[Description("Indonesia")] Indonesia,
			[Description("Ireland")] Ireland,
			[Description("Israel")] Israel,
			[Description("Isle of Man")] IsleofMan,
			[Description("India")] India,
			[Description("British Indian Ocean Territory")] BritishIndianOceanTerritory,
			[Description("Iraq")] Iraq,
			[Description("Iran, Islamic Republic of")] IranIslamicRepublicOf,
			[Description("Iceland")] Iceland,
			[Description("Italy")] Italy,
			[Description("Jersey")] Jersey,
			[Description("Jamaica")] Jamaica,
			[Description("Jordan")] Jordan,
			[Description("Japan")] Japan,
			[Description("Kenya")] Kenya,
			[Description("Kyrgyzstan")] Kyrgyzstan,
			[Description("Cambodia")] Cambodia,
			[Description("Kiribati")] Kiribati,
			[Description("Comoros")] Comoros,
			[Description("Saint Kitts and Nevis")] SaintKittsAndNevis,
			[Description("Korea, Democratic People's Republic of")] KoreaDemocraticPeoplesRepublicOf,
			[Description("Korea, Republic of")] KoreaRepublicof,
			[Description("Kuwait")] Kuwait,
			[Description("Cayman Islands")] CaymanIslands,
			[Description("Kazakhstan")] Kazakhstan,
			[Description("Lao People's Democratic Republic")] LaoPeoplesDemocraticRepublic,
			[Description("Lebanon")] Lebanon,
			[Description("Saint Lucia")] SaintLucia,
			[Description("Liechtenstein")] Liechtenstein,
			[Description("Sri Lanka")] SriLanka,
			[Description("Liberia")] Liberia,
			[Description("Lesotho")] Lesotho,
			[Description("Lithuania")] Lithuania,
			[Description("Luxembourg")] Luxembourg,
			[Description("Latvia")] Latvia,
			[Description("Libya")] Libya,
			[Description("Morocco")] Morocco,
			[Description("Monaco")] Monaco,
			[Description("Moldova, Republic of")] MoldovaRepublicOf,
			[Description("Montenegro")] Montenegro,
			[Description("Saint Martin (French part)")] SaintMartinFrench,
			[Description("Madagascar")] Madagascar,
			[Description("Marshall Islands")] MarshallIslands,
			[Description("Macedonia, the former Yugoslav Republic of")] MacedoniaTheformerYugoslavRepublicOf,
			[Description("Mali")] Mali,
			[Description("Myanmar")] Myanmar,
			[Description("Mongolia")] Mongolia,
			[Description("Macao")] Macao,
			[Description("Northern Mariana Islands")] NorthernMarianaIslands,
			[Description("Martinique")] Martinique,
			[Description("Mauritania")] Mauritania,
			[Description("Montserrat")] Montserrat,
			[Description("Malta")] Malta,
			[Description("Mauritius")] Mauritius,
			[Description("Maldives")] Maldives,
			[Description("Malawi")] Malawi,
			[Description("Mexico")] Mexico,
			[Description("Malaysia")] Malaysia,
			[Description("Mozambique")] Mozambique,
			[Description("Namibia")] Namibia,
			[Description("New Caledonia")] NewCaledonia,
			[Description("Niger")] Niger,
			[Description("Norfolk Island")] NorfolkIsland,
			[Description("Nigeria")] Nigeria,
			[Description("Nicaragua")] Nicaragua,
			[Description("Netherlands")] Netherlands,
			[Description("Norway")] Norway,
			[Description("Nepal")] Nepal,
			[Description("Nauru")] Nauru,
			[Description("Niue")] Niue,
			[Description("New Zealand")] NewZealand,
			[Description("Oman")] Oman,
			[Description("Panama")] Panama,
			[Description("Peru")] Peru,
			[Description("French Polynesia")] FrenchPolynesia,
			[Description("Papua New Guinea")] PapuaNewGuinea,
			[Description("Philippines")] Philippines,
			[Description("Pakistan")] Pakistan,
			[Description("Poland")] Poland,
			[Description("Saint Pierre and Miquelon")] SaintPierreandMiquelon,
			[Description("Pitcairn")] Pitcairn,
			[Description("Puerto Rico")] PuertoRico,
			[Description("Palestine, State of")] PalestineStateOf,
			[Description("Portugal")] Portugal,
			[Description("Palau")] Palau,
			[Description("Paraguay")] Paraguay,
			[Description("Qatar")] Qatar,
			[Description("Réunion")] Réunion,
			[Description("Romania")] Romania,
			[Description("Serbia")] Serbia,
			[Description("Russian Federation")] RussianFederation,
			[Description("Rwanda")] Rwanda,
			[Description("Saudi Arabia")] SaudiArabia,
			[Description("Solomon Islands")] SolomonIslands,
			[Description("Seychelles")] Seychelles,
			[Description("Sudan")] Sudan,
			[Description("Sweden")] Sweden,
			[Description("Singapore")] Singapore,
			[Description("Saint Helena, Ascension and Tristan da Cunha")] SaintHelenaAscensionandTristandaCunha,
			[Description("Slovenia")] Slovenia,
			[Description("Svalbard and Jan Mayen")] SvalbardandJanMayen,
			[Description("Slovakia")] Slovakia,
			[Description("Sierra Leone")] SierraLeone,
			[Description("San Marino")] SanMarino,
			[Description("Senegal")] Senegal,
			[Description("Somalia")] Somalia,
			[Description("Suriname")] Suriname,
			[Description("South Sudan")] SouthSudan,
			[Description("Sao Tome and Principe")] SaoTomeandPrincipe,
			[Description("El Salvador")] ElSalvador,
			[Description("Sint Maarten (Dutch part)")] SintMaartenDutch,
			[Description("Syrian Arab Republic")] SyrianArabRepublic,
			[Description("Swaziland")] Swaziland,
			[Description("Turks and Caicos Islands")] TurksandCaicosIslands,
			[Description("Chad")] Chad,
			[Description("French Southern Territories")] FrenchSouthernTerritories,
			[Description("Togo")] Togo,
			[Description("Thailand")] Thailand,
			[Description("Tajikistan")] Tajikistan,
			[Description("Tokelau")] Tokelau,
			[Description("Timor-Leste")] TimorLeste,
			[Description("Turkmenistan")] Turkmenistan,
			[Description("Tunisia")] Tunisia,
			[Description("Tonga")] Tonga,
			[Description("Turkey")] Turkey,
			[Description("Trinidad and Tobago")] TrinidadandTobago,
			[Description("Tuvalu")] Tuvalu,
			[Description("Taiwan, Province of China")] TaiwanProvinceofChina,
			[Description("Tanzania, United Republic of")] TanzaniaUnitedRepublicof,
			[Description("Ukraine")] Ukraine,
			[Description("Uganda")] Uganda,
			[Description("United States Minor Outlying Islands")] UnitedStatesMinorOutlyingIslands,
			[Description("United States")] UnitedStates,
			[Description("Uruguay")] Uruguay,
			[Description("Uzbekistan")] Uzbekistan,
			[Description("Holy See (Vatican City State)")] HolySeeVaticanCityState,
			[Description("Saint Vincent and the Grenadines")] SaintVincentandtheGrenadines,
			[Description("Venezuela, Bolivarian Republic of")] VenezuelaBolivarianRepublicof,
			[Description("Virgin Islands, British")] VirginIslandsBritish,
			[Description("Virgin Islands, U.S.")] VirginIslandsUs,
			[Description("Viet Nam")] VietNam,
			[Description("Vanuatu")] Vanuatu,
			[Description("Wallis and Futuna")] WallisandFutuna,
			[Description("Samoa")] Samoa,
			[Description("Yemen")] Yemen,
			[Description("Mayotte")] Mayotte,
			[Description("South Africa")] SouthAfrica,
			[Description("Zambia")] Zambia,
			[Description("Zimbabwe")] Zimbabwe,
		}
	}

	internal static class CountryExtensions {
		public static String GetCode(this Search.Country country) {
			switch (country) {
				case Search.Country.Afghanistan:
					return @"<#=country.Code#>";
			}
			throw new NotImplementedException();
		}
	}
}